/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1d8dc89cccd864e8ea04277efc8e4330)
interface __BaseEnv_Env {
	ARCHIVE_DB: D1Database;
	sunshine_hotel_archive: D1Database;
	FIREBASE_PROJECT_ID: "sunshine-staff-portal";
	ALLOWED_ORIGINS: "https://sunshinestaff.consolish.com,http://localhost:3000,http://127.0.0.1:3000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_ID" | "ALLOWED_ORIGINS">> {}
}
